DELETE  http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjJ0ZXN0QGV4YW1wbGUuY29tIiwiZXhwIjoxNzU1NjkyNDYxLCJ1c2VySWQiOjJ9.-b5w8x25usiV5TosBO8JXMivOELrYMwMcs6jcJcvrVs  