DELETE  http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjJ0ZXN0QGV4YW1wbGUuY29tIiwiZXhwIjoxNzU1NjkyNzI0LCJ1c2VySWQiOjJ9.P9qdZTJJPCzPZXQ4Db0BnEALd_MzVFREHU9wuZtgs0w  