DELETE  http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTU2MTI2NzgsInVzZXJJZCI6MX0.3_omyaS4AcAeMaPV9EAbccyxuAYZ6ZKd3GKsw5rlZ04  