DELETE  http://localhost:8080/events/4735f513-424f-49d0-b99a-ac5954d5b567
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjN0ZXN0QGV4YW1wbGUuY29tIiwiZXhwIjoxNzU3Njk5MjkwLCJ1c2VySWQiOjF9.CUZUkfTcMOshT9XttfNZrzm-tgE-ZgG4G8Z_KQvriAg  