POST http://localhost:8080/events/65273ab2-59bc-4b3e-92fc-b261c26bba03/register
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjZ0ZXN0QGV4YW1wbGUuY29tIiwiZXhwIjoxNzU3NDEwODUwLCJ1c2VySWQiOjJ9.1842CdD74i6KeZYxbNJIDsCY2fnPQ36VG-JWRdhEj68

